listening-device=eth0
listening-port=3478
listening-ip=0.0.0.0
relay-ip=0.0.0.0
relay-device=eth0
fingerprint
lt-cred-mech
user=turnuser:turnpass
realm=muninn.local
total-quota=100
stale-nonce=600
external-ip=158.160.123.117
no-udp-relay-ipv6
